addons:
  firefox: latest
language: node_js
node_js:
  - "5.9.0"
before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
install:
  - npm install
  - npm install -g typings
before_script:
  - typings install
script:
  - npm test
  - npm run build:prod
notifications:
  email: false